name: Test

on:
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2 #comment
        with:
          go-version: '^1.18'
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: ${{ hashFiles('go.sum') }}
      - name: Some other tag pinning to a SHA
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      - name: Setup lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
      - name: Test
        run: |
          PATH=$PATH:$(go env GOPATH)/bin make test
      - name: Link Checker
        uses: lycheeverse/lychee-action@c0d1093b783f7ad0c445884b01da0215b2da29ee #v1.4.1
        with:
          fail: true
          args: --exclude-all-private --exclude-file .github/workflows/exclude-file.txt --verbose --no-progress './**/*.md' './**/*.html'